/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package primer_parcial;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Automovil;
import modelo.Avion;
import modelo.Helicoptero;
import modelo.Moto;


/**
 *
 * @author Usuaria
 */
public class frm_vista extends javax.swing.JFrame {

    /**
     * Creates new form frm_vista
     */
    public frm_vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        tabla = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_auto = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_moto = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_avion = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_helicoptero = new javax.swing.JTable();
        titulo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        info = new javax.swing.JTabbedPane();
        automovil = new javax.swing.JDesktopPane();
        placa = new javax.swing.JLabel();
        chasis = new javax.swing.JLabel();
        capacidad = new javax.swing.JLabel();
        serie = new javax.swing.JLabel();
        cilindros = new javax.swing.JLabel();
        tipo = new javax.swing.JLabel();
        marca = new javax.swing.JLabel();
        modelo = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        motor = new javax.swing.JLabel();
        txt_chasisa = new javax.swing.JTextField();
        txt_placa = new javax.swing.JTextField();
        txt_capacidad = new javax.swing.JTextField();
        txt_serie = new javax.swing.JTextField();
        txt_tipo = new javax.swing.JTextField();
        txt_cilindros = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_modelo = new javax.swing.JTextField();
        txt_color = new javax.swing.JTextField();
        txt_motor = new javax.swing.JTextField();
        txt_precio = new javax.swing.JTextField();
        Agregar_auto = new javax.swing.JButton();
        moto = new javax.swing.JDesktopPane();
        Velocidades = new javax.swing.JLabel();
        txt_velocidades = new javax.swing.JTextField();
        tipo_de_motor = new javax.swing.JLabel();
        txt_tipo_de_moto = new javax.swing.JTextField();
        Velocidades2 = new javax.swing.JLabel();
        javax.swing.JTextField txt_capacidadm = new javax.swing.JTextField();
        Velocidades3 = new javax.swing.JLabel();
        txt_placam = new javax.swing.JTextField();
        Velocidades4 = new javax.swing.JLabel();
        txt_chasism = new javax.swing.JTextField();
        Velocidades5 = new javax.swing.JLabel();
        txt_seriem = new javax.swing.JTextField();
        Velocidades6 = new javax.swing.JLabel();
        txt_cilindrosm = new javax.swing.JTextField();
        Velocidades7 = new javax.swing.JLabel();
        txt_tipom = new javax.swing.JTextField();
        Velocidades8 = new javax.swing.JLabel();
        txt_marcam = new javax.swing.JTextField();
        Velocidades9 = new javax.swing.JLabel();
        txt_colorm = new javax.swing.JTextField();
        Velocidades10 = new javax.swing.JLabel();
        txt_preciom = new javax.swing.JTextField();
        Velocidades11 = new javax.swing.JLabel();
        txt_motorm = new javax.swing.JTextField();
        Velocidades12 = new javax.swing.JLabel();
        agregar_moto = new javax.swing.JButton();
        avion = new javax.swing.JDesktopPane();
        agregar_avion = new javax.swing.JButton();
        Velocidades13 = new javax.swing.JLabel();
        Velocidades14 = new javax.swing.JLabel();
        Veloci = new javax.swing.JLabel();
        Velocidades16 = new javax.swing.JLabel();
        Velocidades17 = new javax.swing.JLabel();
        Velocidades18 = new javax.swing.JLabel();
        txt_marca_avion = new javax.swing.JTextField();
        txt_am = new javax.swing.JTextField();
        txt_transporte = new javax.swing.JTextField();
        txt_tren = new javax.swing.JTextField();
        txt_alas = new javax.swing.JTextField();
        txt_aereolineas = new javax.swing.JTextField();
        Velocidades19 = new javax.swing.JLabel();
        Velocidades21 = new javax.swing.JLabel();
        Velocidades22 = new javax.swing.JLabel();
        Velocidades24 = new javax.swing.JLabel();
        txt_motor_avion = new javax.swing.JTextField();
        txt_precio_avion = new javax.swing.JTextField();
        txt_color_avion = new javax.swing.JTextField();
        txt_modelo_avion = new javax.swing.JTextField();
        Helicoptero = new javax.swing.JDesktopPane();
        agregar_helicoptero = new javax.swing.JButton();
        Velocidades25 = new javax.swing.JLabel();
        txt_helices = new javax.swing.JTextField();
        Velocidades27 = new javax.swing.JLabel();
        txt_trendeaterrizaje = new javax.swing.JTextField();
        Velocidades28 = new javax.swing.JLabel();
        txt_tipo_de_trasporte = new javax.swing.JTextField();
        Velocidades29 = new javax.swing.JLabel();
        txt_amh = new javax.swing.JTextField();
        Velocidades30 = new javax.swing.JLabel();
        Velocidades31 = new javax.swing.JLabel();
        txt_modeloh = new javax.swing.JTextField();
        Velocidades32 = new javax.swing.JLabel();
        txt_colorh = new javax.swing.JTextField();
        Velocidades33 = new javax.swing.JLabel();
        txt_precioh = new javax.swing.JTextField();
        Velocidades34 = new javax.swing.JLabel();
        txt_motorh = new javax.swing.JTextField();
        txt_marcah = new javax.swing.JTextField();
        vt_1 = new javax.swing.JLabel();
        va_1 = new javax.swing.JLabel();
        vt_2 = new javax.swing.JLabel();
        va_2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tabla.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbl_auto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbl_auto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "Chasis", "Capacidad", "Serie", "Cilidros", "Tipo", "Marca", "Modelo", "Color", "Precio", "Motor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_auto);

        tabla.addTab("Automovil", jScrollPane1);

        tbl_moto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbl_moto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Velocidades", "Tipo de Moto", "Capacidad", "Placa", "Chasis", "Serie", "Cilindros", "TIpo", "Marca", "Color", "Precio", "Motor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_moto);

        tabla.addTab("Moto", jScrollPane2);

        tbl_avion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbl_avion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Aereolinia", "Alas", "Tren de aterrizaje", "Tipo de Transporte", "Altitud Maxima", "Marca", "Modelo", "Color", "Precio", "Motor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tbl_avion);

        tabla.addTab("Avion", jScrollPane3);

        tbl_helicoptero.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tbl_helicoptero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "No. de helices", "Tren de aterrizaje", "Tipo de transporte", "Altitud Maxima", "Marca", "Modelo", "Color", "Precio", "Motor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbl_helicoptero);

        tabla.addTab("Helicoptero", jScrollPane4);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabla)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabla, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        titulo.setFont(new java.awt.Font("Georgia", 1, 48)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Vehiculos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        automovil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        placa.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        placa.setText("Placa");

        chasis.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        chasis.setText("Chasis");

        capacidad.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        capacidad.setText("Capacidad");

        serie.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        serie.setText("Serie");

        cilindros.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        cilindros.setText("Cilindros");

        tipo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        tipo.setText("Tipo");

        marca.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        marca.setText("Marca");

        modelo.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        modelo.setText("Modelo");

        color.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        color.setText("Color");

        precio.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        precio.setText("Precio");

        motor.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        motor.setText("Motor");

        txt_chasisa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_placa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_capacidad.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_serie.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_tipo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_cilindros.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_cilindros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cilindrosActionPerformed(evt);
            }
        });

        txt_marca.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_modelo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_color.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_colorActionPerformed(evt);
            }
        });

        txt_motor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_motor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_motorActionPerformed(evt);
            }
        });

        txt_precio.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_precioActionPerformed(evt);
            }
        });

        Agregar_auto.setBackground(new java.awt.Color(153, 153, 153));
        Agregar_auto.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        Agregar_auto.setForeground(new java.awt.Color(153, 153, 153));
        Agregar_auto.setText("Agregar");
        Agregar_auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_autoActionPerformed(evt);
            }
        });

        automovil.setLayer(placa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(chasis, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(capacidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(serie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(cilindros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(tipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(marca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(modelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(color, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(precio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(motor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(txt_chasisa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(txt_placa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(txt_capacidad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(txt_serie, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(txt_tipo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(txt_cilindros, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(txt_marca, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(txt_modelo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(txt_color, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(txt_motor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(txt_precio, javax.swing.JLayeredPane.DEFAULT_LAYER);
        automovil.setLayer(Agregar_auto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout automovilLayout = new javax.swing.GroupLayout(automovil);
        automovil.setLayout(automovilLayout);
        automovilLayout.setHorizontalGroup(
            automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(automovilLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(capacidad)
                    .addComponent(chasis, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(placa, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(serie, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cilindros, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tipo, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(38, 38, 38)
                .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(automovilLayout.createSequentialGroup()
                        .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_chasisa, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_serie, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cilindros, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108)
                        .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_motor, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(automovilLayout.createSequentialGroup()
                                .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(modelo)
                                        .addComponent(marca, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(color)
                                    .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(motor)
                                        .addComponent(precio)))
                                .addGap(18, 18, 18)
                                .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_marca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(89, 89, 89)
                        .addComponent(Agregar_auto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        automovilLayout.setVerticalGroup(
            automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(automovilLayout.createSequentialGroup()
                .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(automovilLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(placa)
                            .addComponent(marca)
                            .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(chasis)
                            .addComponent(modelo)
                            .addComponent(txt_chasisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(capacidad)
                            .addComponent(color)
                            .addComponent(txt_capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(serie)
                                .addComponent(precio)
                                .addComponent(txt_serie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, automovilLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(Agregar_auto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(automovilLayout.createSequentialGroup()
                        .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(motor)
                            .addComponent(txt_motor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, automovilLayout.createSequentialGroup()
                        .addGap(0, 6, Short.MAX_VALUE)
                        .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cilindros)
                            .addComponent(txt_cilindros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(automovilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipo)
                    .addComponent(txt_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        info.addTab("Automovil", automovil);

        Velocidades.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades.setText("Velocidades");

        txt_velocidades.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        tipo_de_motor.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        tipo_de_motor.setText("Tipo de moto");

        txt_tipo_de_moto.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades2.setText("Capacidad");

        txt_capacidadm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades3.setText("Placa");

        txt_placam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades4.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades4.setText("Chasis");

        txt_chasism.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades5.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades5.setText("Serie");

        txt_seriem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades6.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades6.setText("Cilindros");

        txt_cilindrosm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades7.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades7.setText("Tipo");

        txt_tipom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades8.setText("Marca");

        txt_marcam.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades9.setText("Color");

        txt_colorm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N

        txt_preciom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades11.setText("Motor");

        txt_motorm.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades12.setText("Precio");

        agregar_moto.setBackground(new java.awt.Color(153, 153, 153));
        agregar_moto.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        agregar_moto.setForeground(new java.awt.Color(153, 153, 153));
        agregar_moto.setText("Agregar");
        agregar_moto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_motoActionPerformed(evt);
            }
        });

        moto.setLayer(Velocidades, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(txt_velocidades, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(tipo_de_motor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(txt_tipo_de_moto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(Velocidades2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(txt_capacidadm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(Velocidades3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(txt_placam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(Velocidades4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(txt_chasism, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(Velocidades5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(txt_seriem, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(Velocidades6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(txt_cilindrosm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(Velocidades7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(txt_tipom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(Velocidades8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(txt_marcam, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(Velocidades9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(txt_colorm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(Velocidades10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(txt_preciom, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(Velocidades11, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(txt_motorm, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(Velocidades12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        moto.setLayer(agregar_moto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout motoLayout = new javax.swing.GroupLayout(moto);
        moto.setLayout(motoLayout);
        motoLayout.setHorizontalGroup(
            motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(motoLayout.createSequentialGroup()
                        .addComponent(Velocidades)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_velocidades, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(motoLayout.createSequentialGroup()
                        .addComponent(Velocidades5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_seriem, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, motoLayout.createSequentialGroup()
                        .addComponent(Velocidades4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_chasism, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, motoLayout.createSequentialGroup()
                        .addComponent(Velocidades3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_placam, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(motoLayout.createSequentialGroup()
                        .addComponent(Velocidades2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_capacidadm, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(motoLayout.createSequentialGroup()
                        .addComponent(tipo_de_motor)
                        .addGap(18, 18, 18)
                        .addComponent(txt_tipo_de_moto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Velocidades10)
                    .addGroup(motoLayout.createSequentialGroup()
                        .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Velocidades6)
                            .addComponent(Velocidades11)
                            .addComponent(Velocidades12)
                            .addComponent(Velocidades8)
                            .addComponent(Velocidades9)
                            .addComponent(Velocidades7))
                        .addGap(18, 18, 18)
                        .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tipom, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_motorm, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cilindrosm, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_preciom, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(motoLayout.createSequentialGroup()
                                .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_marcam, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_colorm, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(126, 126, 126)
                                .addComponent(agregar_moto, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(271, Short.MAX_VALUE))
        );
        motoLayout.setVerticalGroup(
            motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motoLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(motoLayout.createSequentialGroup()
                        .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades6)
                            .addComponent(txt_cilindrosm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tipom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Velocidades7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades8)
                            .addComponent(txt_marcam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregar_moto, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_colorm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Velocidades9))
                        .addGap(22, 22, 22)
                        .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades10)
                            .addComponent(txt_preciom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Velocidades12))
                        .addGap(18, 18, 18)
                        .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades11)
                            .addComponent(txt_motorm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(motoLayout.createSequentialGroup()
                        .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades)
                            .addComponent(txt_velocidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tipo_de_motor)
                            .addComponent(txt_tipo_de_moto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades2)
                            .addComponent(txt_capacidadm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades3)
                            .addComponent(txt_placam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades4)
                            .addComponent(txt_chasism, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(motoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades5)
                            .addComponent(txt_seriem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        info.addTab("Moto", moto);

        agregar_avion.setBackground(new java.awt.Color(153, 153, 153));
        agregar_avion.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        agregar_avion.setForeground(new java.awt.Color(153, 153, 153));
        agregar_avion.setText("Agregar");
        agregar_avion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_avionActionPerformed(evt);
            }
        });

        Velocidades13.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades13.setText("Aereolinea");

        Velocidades14.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades14.setText("Alas");

        Veloci.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Veloci.setText("Tren de aterrizaje");

        Velocidades16.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades16.setText("Tipo de Transporte");

        Velocidades17.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades17.setText("Altitud Maxima");

        Velocidades18.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades18.setText("Marca");

        txt_marca_avion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_am.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_transporte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_tren.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_alas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_aereolineas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txt_aereolineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_aereolineasActionPerformed(evt);
            }
        });

        Velocidades19.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades19.setText("Modelo");

        Velocidades21.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades21.setText("Color");

        Velocidades22.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades22.setText("Precio");

        Velocidades24.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades24.setText("Motor");

        txt_motor_avion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_precio_avion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_color_avion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_modelo_avion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        avion.setLayer(agregar_avion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(Velocidades13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(Velocidades14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(Veloci, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(Velocidades16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(Velocidades17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(Velocidades18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(txt_marca_avion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(txt_am, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(txt_transporte, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(txt_tren, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(txt_alas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(txt_aereolineas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(Velocidades19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(Velocidades21, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(Velocidades22, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(Velocidades24, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(txt_motor_avion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(txt_precio_avion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(txt_color_avion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        avion.setLayer(txt_modelo_avion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout avionLayout = new javax.swing.GroupLayout(avion);
        avion.setLayout(avionLayout);
        avionLayout.setHorizontalGroup(
            avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avionLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(avionLayout.createSequentialGroup()
                        .addComponent(Velocidades13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_aereolineas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avionLayout.createSequentialGroup()
                        .addComponent(Velocidades17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_am, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avionLayout.createSequentialGroup()
                        .addComponent(Velocidades16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_transporte, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(avionLayout.createSequentialGroup()
                        .addComponent(Veloci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_tren, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(avionLayout.createSequentialGroup()
                        .addComponent(Velocidades14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_alas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(94, 94, 94)
                .addGroup(avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(avionLayout.createSequentialGroup()
                        .addComponent(Velocidades24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_motor_avion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(avionLayout.createSequentialGroup()
                        .addComponent(Velocidades18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_marca_avion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(avionLayout.createSequentialGroup()
                        .addComponent(Velocidades19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addComponent(txt_modelo_avion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avionLayout.createSequentialGroup()
                        .addComponent(Velocidades22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_precio_avion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avionLayout.createSequentialGroup()
                        .addComponent(Velocidades21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_color_avion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(91, 91, 91)
                .addComponent(agregar_avion, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(165, 165, 165))
        );
        avionLayout.setVerticalGroup(
            avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avionLayout.createSequentialGroup()
                .addGroup(avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(avionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades13)
                            .addComponent(txt_aereolineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Velocidades18)
                            .addComponent(txt_marca_avion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades14)
                            .addComponent(txt_alas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Veloci)
                            .addComponent(txt_tren, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades16)
                            .addComponent(txt_transporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(avionLayout.createSequentialGroup()
                        .addGroup(avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(avionLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addGroup(avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Velocidades19)
                                    .addComponent(txt_modelo_avion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(avionLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(agregar_avion, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades21)
                            .addComponent(txt_color_avion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_precio_avion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Velocidades22))))
                .addGap(29, 29, 29)
                .addGroup(avionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Velocidades17)
                    .addComponent(txt_am, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Velocidades24)
                    .addComponent(txt_motor_avion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        info.addTab("Avion", avion);

        agregar_helicoptero.setBackground(new java.awt.Color(153, 153, 153));
        agregar_helicoptero.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        agregar_helicoptero.setForeground(new java.awt.Color(153, 153, 153));
        agregar_helicoptero.setText("Agregar");
        agregar_helicoptero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_helicopteroActionPerformed(evt);
            }
        });

        Velocidades25.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades25.setText("No. de Helices");

        txt_helices.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades27.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades27.setText("Tren de aterrizaje");

        txt_trendeaterrizaje.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades28.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades28.setText("Tipo de Transporte");

        txt_tipo_de_trasporte.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades29.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades29.setText("Altitud Maxima");

        txt_amh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades30.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades30.setText("Marca");

        Velocidades31.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades31.setText("Modelo");

        txt_modeloh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades32.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades32.setText("Color");

        txt_colorh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades33.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades33.setText("Precio");

        txt_precioh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Velocidades34.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Velocidades34.setText("Motor");

        txt_motorh.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        txt_marcah.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        Helicoptero.setLayer(agregar_helicoptero, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(Velocidades25, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(txt_helices, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(Velocidades27, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(txt_trendeaterrizaje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(Velocidades28, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(txt_tipo_de_trasporte, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(Velocidades29, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(txt_amh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(Velocidades30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(Velocidades31, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(txt_modeloh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(Velocidades32, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(txt_colorh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(Velocidades33, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(txt_precioh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(Velocidades34, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(txt_motorh, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Helicoptero.setLayer(txt_marcah, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout HelicopteroLayout = new javax.swing.GroupLayout(Helicoptero);
        Helicoptero.setLayout(HelicopteroLayout);
        HelicopteroLayout.setHorizontalGroup(
            HelicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HelicopteroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(HelicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(HelicopteroLayout.createSequentialGroup()
                        .addComponent(Velocidades30)
                        .addGap(103, 103, 103)
                        .addComponent(txt_marcah, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HelicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HelicopteroLayout.createSequentialGroup()
                            .addComponent(Velocidades29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_amh, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HelicopteroLayout.createSequentialGroup()
                            .addComponent(Velocidades28)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_tipo_de_trasporte, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(HelicopteroLayout.createSequentialGroup()
                            .addComponent(Velocidades27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_trendeaterrizaje, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HelicopteroLayout.createSequentialGroup()
                        .addComponent(Velocidades25)
                        .addGap(37, 37, 37)
                        .addComponent(txt_helices, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addGroup(HelicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HelicopteroLayout.createSequentialGroup()
                        .addComponent(Velocidades34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_motorh, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HelicopteroLayout.createSequentialGroup()
                        .addComponent(Velocidades31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(txt_modeloh, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HelicopteroLayout.createSequentialGroup()
                        .addComponent(Velocidades33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_precioh, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HelicopteroLayout.createSequentialGroup()
                        .addComponent(Velocidades32)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_colorh, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(118, 118, 118)
                .addComponent(agregar_helicoptero, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        HelicopteroLayout.setVerticalGroup(
            HelicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HelicopteroLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(HelicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HelicopteroLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(HelicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades27)
                            .addComponent(txt_trendeaterrizaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(agregar_helicoptero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(HelicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades28)
                            .addComponent(txt_tipo_de_trasporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(HelicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades29)
                            .addComponent(txt_amh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(HelicopteroLayout.createSequentialGroup()
                        .addGroup(HelicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades31)
                            .addComponent(txt_modeloh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Velocidades25)
                            .addComponent(txt_helices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(HelicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades32)
                            .addComponent(txt_colorh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(HelicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_precioh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Velocidades33))
                        .addGap(29, 29, 29)
                        .addGroup(HelicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Velocidades34)
                            .addComponent(txt_motorh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(HelicopteroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Velocidades30)
                    .addComponent(txt_marcah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        info.addTab("Helicoptero", Helicoptero);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 1162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(info, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        vt_1.setText("Vehiculos Terrestres");

        va_1.setText("Vehiculos Aereos");

        vt_2.setText("Vehiculos Terrestres");

        va_2.setText("Vehiculos Aereos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(vt_1)
                        .addGap(18, 18, 18)
                        .addComponent(va_1)
                        .addGap(42, 42, 42)
                        .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vt_2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(va_2))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vt_1)
                        .addComponent(va_1))
                    .addComponent(titulo))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vt_2)
                    .addComponent(va_2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_cilindrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cilindrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cilindrosActionPerformed

    private void txt_colorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_colorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_colorActionPerformed

    private void txt_precioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_precioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_precioActionPerformed

    private void txt_motorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_motorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_motorActionPerformed

    private void Agregar_autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_autoActionPerformed
        Automovil av = new Automovil(
                                this.txt_placa.getText(),
                                this.txt_chasisa.getText(),
                                this.txt_capacidad.getText(),
                                this.txt_serie.getText(),
                                this.txt_cilindros.getText(),
                                this.txt_tipo.getText(),
                                this.txt_marca.getText(),
                                this.txt_modelo.getText(),
                                this.txt_color.getText(),
                                this.txt_precio.getText(),
                                this.txt_motor.getText());
           
      
          lista1.add(av);
               mostrar();
        
                                                 
public void mostrar (){
    String matris[][]=new String [lista1.size()][11];
    for (int i= 0; i < lista1.size (); i++){
     matris [i][0]= lista1.get(i).getCapacidad();
     matris [i][1]= lista1.get(i).getPlaca();
     matris [i][2]= lista1.get(i).getChasis();
     matris [i][3]= lista1.get(i).getSerie();
     matris [i][4]= lista1.get(i).getCilindros();
     matris [i][5]= lista1.get(i).getTipo();
     matris [i][6]= lista1.get(i).getMarca();
     matris [i][7]= lista1.get(i).getModelo();
     matris [i][8]= lista1.get(i).getColor();
     matris [i][9]= lista1.get(i).getPrecio();
     matris [i][10]= lista1.get(i).getMotor();
        
    
        }
        
    tbl_auto.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Capacidad", "Placa", "Chasis", "Serie","Cilindros", "Tipo" ,"Marca", "Modelo", "Color", "Precio", "Motor"
                     }));
    
    }    
    }          
    }//GEN-LAST:event_Agregar_autoActionPerformed

    private void txt_aereolineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_aereolineasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_aereolineasActionPerformed

    private void agregar_avionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_avionActionPerformed
        // TODO add your handling code here:
                
        Avion av = new Avion(this.txt_aereolineas.getText(),
                                this.txt_alas.getText(),
                                this.txt_tren.getText(),
                                this.txt_transporte.getText(),
                                this.txt_am.getText(),
                                this.txt_marca_avion.getText(),
                                this.txt_modelo_avion.getText(),
                                this.txt_color_avion.getText(),
                                this.txt_precio_avion.getText(),
                                this.txt_motor_avion.getText());
           
      
          lista.add(av);
               mostrar();
        
                                                 
public void mostrar (){
    String matris[][]=new String [lista3.size()][10];
    for (int i= 0; i < lista3.size (); i++){
     matris [i][0]= lista3.get(i).getAereolinea();
     matris [i][1]= lista3.get(i).getAlas();
     matris [i][2]= lista3.get(i).getTren_aterrizaje();
     matris [i][3]= lista3.get(i).getTipo_transporte();
     matris [i][4]= lista3.get(i).getAltitud_maxima();
     matris [i][5]= lista3.get(i).getMarca();
     matris [i][6]= lista3.get(i).getModelo();
     matris [i][7]= lista3.get(i).getColor();
     matris [i][8]= lista3.get(i).getPrecio();
     matris [i][9]= lista3.get(i).getMotor();
        
    
        }
        
    tbl_avion.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Aerolinea", "Alas", "Tren de aterrizaje", "Tipo de Transporte", "Altitud Maxima", "Marca", "Modelo", "Color", "Precio", "Motor"
                     }));
    
    }//GEN-LAST:event_agregar_avionActionPerformed

    private void agregar_helicopteroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_helicopteroActionPerformed
        // TODO add your handling code here:
         Helicoptero h = new Helicoptero(
                                this.txt_helices.getText(),
                                this.txt_trendeaterrizaje.getText(),
                                this.txt_tipo_de_trasporte.getText(),
                                this.txt_amh.getText(),
                                this.txt_marcah.getText(),
                                this.txt_modeloh.getText(),
                                this.txt_colorh.getText(),
                                this.txt_precioh.getText(),
                                this.txt_motorh.getText());
           
      
          lista4.add(h);
               mostrar();
        
                                                 
public void mostrar (){
    String matris[][]=new String [lista4.size()][9];
    for (int i= 0; i < lista4.size (); i++){
     matris [i][0]= lista4.get(i).getNo_helices();
     matris [i][1]= lista4.get(i).getTren_aterrizaje();
     matris [i][2]= lista4.get(i).getTipo_transporte();
     matris [i][3]= lista4.get(i).getAltitud_maxima();
     matris [i][4]= lista4.get(i).getMarca();
     matris [i][5]= lista4.get(i).getModelo();
     matris [i][6]= lista4.get(i).getColor();
     matris [i][7]= lista4.get(i).getPrecio();
     matris [i][8]= lista4.get(i).getMotor();
        
    
        }
        
    tbl_helicoptero.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "No. de helices", "Tren de aterrizaje", "Tipo de Transporte", "Altitud Maxima", "Marca", "Modelo", "Color", "Precio", "Motor"
                     }));
    
    }    
    }//GEN-LAST:event_agregar_helicopteroActionPerformed

    private void agregar_motoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_motoActionPerformed
        // TODO add your handling code here:
         Moto mt = new Moto(
                                this.txt_velocidades.getText(),
                                this.txt_tipo_de_moto.getText(),
                                this.txt_capacidadm.getText(),
                                this.txt_placam.getText(),
                                this.txt_chasism.getText(),
                                this.txt_seriem.getText(),
                                this.txt_cilindrosm.getText(),
                                this.txt_tipom.getText(),        
                                this.txt_marcam.getText(),
                                this.txt_modelom.getText(),
                                this.txt_colorm.getText(),
                                this.txt_preciom.getText(),
                                this.txt_motorm.getText());
           
      
          lista2.add(mt);
               mostrar();
        
                                                 
public void mostrar (){
    String matris[][]=new String [lista2.size()][13];
    for (int i= 0; i < lista2.size (); i++){
     matris [i][0]= lista2.get(i).getVelocidades();
     matris [i][1]= lista2.get(i).getTipo_moto();
     matris [i][2]= lista2.get(i).getCapacidad();
     matris [i][3]= lista2.get(i).getPlaca();
     matris [i][4]= lista2.get(i).getChasis();
     matris [i][5]= lista2.get(i).getSerie();
     matris [i][6]= lista2.get(i).getCilindros();
     matris [i][7]= lista2.get(i).getTipo();
     matris [i][8]= lista2.get(i).getMarca();
     matris [i][9]= lista2.get(i).getModelo();
     matris [i][10]= lista2.get(i).getColor();
     matris [i][11]= lista2.get(i).getPrecio();
     matris [i][12]= lista2.get(i).getMotor();
        
    
        }
        
    tbl_moto.setModel(new javax.swing.table.DefaultTableModel(
            matris,
            new String [] {
                "Capacidad", "Placa", "Chasis", "Serie","Cilindros", "Tipo" ,"Marca", "Modelo", "Color", "Precio", "Motor"
                     }));
    
    }    
    }     
    }//GEN-LAST:event_agregar_motoActionPerformed
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregar_auto;
    private javax.swing.JDesktopPane Helicoptero;
    private javax.swing.JLabel Veloci;
    private javax.swing.JLabel Velocidades;
    private javax.swing.JLabel Velocidades10;
    private javax.swing.JLabel Velocidades11;
    private javax.swing.JLabel Velocidades12;
    private javax.swing.JLabel Velocidades13;
    private javax.swing.JLabel Velocidades14;
    private javax.swing.JLabel Velocidades16;
    private javax.swing.JLabel Velocidades17;
    private javax.swing.JLabel Velocidades18;
    private javax.swing.JLabel Velocidades19;
    private javax.swing.JLabel Velocidades2;
    private javax.swing.JLabel Velocidades21;
    private javax.swing.JLabel Velocidades22;
    private javax.swing.JLabel Velocidades24;
    private javax.swing.JLabel Velocidades25;
    private javax.swing.JLabel Velocidades27;
    private javax.swing.JLabel Velocidades28;
    private javax.swing.JLabel Velocidades29;
    private javax.swing.JLabel Velocidades3;
    private javax.swing.JLabel Velocidades30;
    private javax.swing.JLabel Velocidades31;
    private javax.swing.JLabel Velocidades32;
    private javax.swing.JLabel Velocidades33;
    private javax.swing.JLabel Velocidades34;
    private javax.swing.JLabel Velocidades4;
    private javax.swing.JLabel Velocidades5;
    private javax.swing.JLabel Velocidades6;
    private javax.swing.JLabel Velocidades7;
    private javax.swing.JLabel Velocidades8;
    private javax.swing.JLabel Velocidades9;
    private javax.swing.JButton agregar_avion;
    private javax.swing.JButton agregar_helicoptero;
    private javax.swing.JButton agregar_moto;
    private javax.swing.JDesktopPane automovil;
    private javax.swing.JDesktopPane avion;
    private javax.swing.JLabel capacidad;
    private javax.swing.JLabel chasis;
    private javax.swing.JLabel cilindros;
    private javax.swing.JLabel color;
    private javax.swing.JTabbedPane info;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel marca;
    private javax.swing.JLabel modelo;
    private javax.swing.JDesktopPane moto;
    private javax.swing.JLabel motor;
    private javax.swing.JLabel placa;
    private javax.swing.JLabel precio;
    private javax.swing.JLabel serie;
    private javax.swing.JTabbedPane tabla;
    private javax.swing.JTable tbl_auto;
    private javax.swing.JTable tbl_avion;
    private javax.swing.JTable tbl_helicoptero;
    private javax.swing.JTable tbl_moto;
    private javax.swing.JLabel tipo;
    private javax.swing.JLabel tipo_de_motor;
    private javax.swing.JLabel titulo;
    private javax.swing.JTextField txt_aereolineas;
    private javax.swing.JTextField txt_alas;
    private javax.swing.JTextField txt_am;
    private javax.swing.JTextField txt_amh;
    private javax.swing.JTextField txt_capacidad;
    private javax.swing.JTextField txt_chasisa;
    private javax.swing.JTextField txt_chasism;
    private javax.swing.JTextField txt_cilindros;
    private javax.swing.JTextField txt_cilindrosm;
    private javax.swing.JTextField txt_color;
    private javax.swing.JTextField txt_color_avion;
    private javax.swing.JTextField txt_colorh;
    private javax.swing.JTextField txt_colorm;
    private javax.swing.JTextField txt_helices;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_marca_avion;
    private javax.swing.JTextField txt_marcah;
    private javax.swing.JTextField txt_marcam;
    private javax.swing.JTextField txt_modelo;
    private javax.swing.JTextField txt_modelo_avion;
    private javax.swing.JTextField txt_modeloh;
    private javax.swing.JTextField txt_motor;
    private javax.swing.JTextField txt_motor_avion;
    private javax.swing.JTextField txt_motorh;
    private javax.swing.JTextField txt_motorm;
    private javax.swing.JTextField txt_placa;
    private javax.swing.JTextField txt_placam;
    private javax.swing.JTextField txt_precio;
    private javax.swing.JTextField txt_precio_avion;
    private javax.swing.JTextField txt_precioh;
    private javax.swing.JTextField txt_preciom;
    private javax.swing.JTextField txt_serie;
    private javax.swing.JTextField txt_seriem;
    private javax.swing.JTextField txt_tipo;
    private javax.swing.JTextField txt_tipo_de_moto;
    private javax.swing.JTextField txt_tipo_de_trasporte;
    private javax.swing.JTextField txt_tipom;
    private javax.swing.JTextField txt_transporte;
    private javax.swing.JTextField txt_tren;
    private javax.swing.JTextField txt_trendeaterrizaje;
    private javax.swing.JTextField txt_velocidades;
    private javax.swing.JLabel va_1;
    private javax.swing.JLabel va_2;
    private javax.swing.JLabel vt_1;
    private javax.swing.JLabel vt_2;
    // End of variables declaration//GEN-END:variables
}
